/**
 * Daily agenda email — runs every hour, checks whether it's currently
 * 8:00 AM local time (relative to whichever city that day's agenda is in)
 * for any day of the trip, and if so emails everyone the day's plan.
 *
 * Data flow:
 *   - The itinerary itself is NOT stored here. It's fetched fresh, on every
 *     run, from itinerary-feed.json on the live site (regenerated by
 *     build.py every time the agenda changes). This means the site owner
 *     never has to redeploy this function when the agenda changes — only
 *     when this file itself changes.
 *   - Participants (name + email) live in Firestore, collection
 *     "participants", one document per person: { name, email }.
 *     Add these directly in the Firebase Console once you have them.
 *   - A Firestore doc in "emailSentLog/{date}" marks a day as already
 *     emailed, so a re-run within the same hour (or a scheduler retry)
 *     never sends duplicates.
 *
 * Required setup (see functions/README.md for full steps):
 *   1. Firebase project on the Blaze (pay-as-you-go) plan.
 *   2. A Resend account (resend.com) — free tier, 3,000 emails/month.
 *   3. Set the Resend API key as a Firebase secret:
 *        firebase functions:secrets:set RESEND_API_KEY
 *   4. Update ITINERARY_FEED_URL and FROM_EMAIL below.
 *   5. Deploy: firebase deploy --only functions
 */

const { onSchedule } = require("firebase-functions/v2/scheduler");
const { defineSecret } = require("firebase-functions/params");
const { logger } = require("firebase-functions");
const admin = require("firebase-admin");

admin.initializeApp();
const db = admin.firestore();

const RESEND_API_KEY = defineSecret("RESEND_API_KEY");

// ---- Configure these two before deploying ----
const ITINERARY_FEED_URL = "https://REPLACE-WITH-YOUR-GITHUB-USERNAME.github.io/paris-london-2026/itinerary-feed.json";
const FROM_EMAIL = "Trip Agenda <onboarding@resend.dev>"; // swap for a verified domain sender once you have one
// -----------------------------------------------

function currentLocalHourAndDate(timeZone) {
  const now = new Date();
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", hour12: false
  }).formatToParts(now);
  const get = (type) => parts.find((p) => p.type === type).value;
  return {
    date: `${get("year")}-${get("month")}-${get("day")}`,
    hour: parseInt(get("hour"), 10)
  };
}

function renderEventRow(ev) {
  const noteHtml = ev.note ? `<div style="color:#726c60;font-size:13px;margin-top:2px;">${escapeHtml(ev.note)}</div>` : "";
  const tag = ev.placeholder ? ' <span style="color:#a07c40;font-style:italic;">(tentative)</span>' : "";
  return `<tr>
    <td style="padding:8px 12px 8px 0;font-family:monospace;font-size:13px;color:#726c60;white-space:nowrap;vertical-align:top;">${escapeHtml(ev.time || "—")}</td>
    <td style="padding:8px 0;border-top:1px solid #e2d9c6;">
      <div style="font-weight:600;color:#201e1b;">${escapeHtml(ev.title)}${tag}</div>
      ${noteHtml}
    </td>
  </tr>`;
}

function escapeHtml(str) {
  return String(str || "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[c]));
}

function buildEmailHtml(day, tripTitle, siteUrl) {
  const rows = (day.events || []).map(renderEventRow).join("");
  const hotelLine = day.hotel ? `<p style="color:#726c60;font-size:14px;">Staying at <b>${escapeHtml(day.hotel)}</b></p>` : "";
  return `<!DOCTYPE html>
<html><body style="margin:0;padding:0;background:#faf7f1;font-family:-apple-system,Helvetica,Arial,sans-serif;">
<div style="max-width:560px;margin:0 auto;padding:24px 20px;">
  <p style="font-family:monospace;font-size:12px;letter-spacing:0.06em;text-transform:uppercase;color:#a07c40;margin:0 0 4px;">${escapeHtml(tripTitle)} &middot; ${escapeHtml(day.city_label)}</p>
  <h1 style="font-size:28px;margin:0 0 4px;color:#201e1b;">${escapeHtml(day.display_date)}</h1>
  <p style="color:#726c60;margin:0 0 4px;">${escapeHtml(day.weekday)} &middot; ${escapeHtml(day.kicker)}</p>
  ${hotelLine}
  <table style="width:100%;border-collapse:collapse;margin-top:16px;">${rows}</table>
  <p style="margin-top:28px;"><a href="${siteUrl}" style="color:#1d4e89;">Open the full site &rarr;</a></p>
</div>
</body></html>`;
}

async function sendEmail(apiKey, toEmail, subject, html) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to: [toEmail],
      subject,
      html
    })
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend API error ${res.status}: ${body}`);
  }
}

exports.dailyAgendaEmail = onSchedule(
  { schedule: "every 1 hours", secrets: [RESEND_API_KEY] },
  async () => {
    let feed;
    try {
      const res = await fetch(ITINERARY_FEED_URL, { cache: "no-store" });
      feed = await res.json();
    } catch (err) {
      logger.error("Could not fetch itinerary feed", err);
      return;
    }

    for (const day of feed.days) {
      const { date, hour } = currentLocalHourAndDate(day.email_timezone);
      if (date !== day.date || hour !== 8) continue; // only fire at 8am local, on the matching date

      const sentLogRef = db.collection("emailSentLog").doc(day.date);
      const sentLogDoc = await sentLogRef.get();
      if (sentLogDoc.exists) {
        logger.info(`Already sent for ${day.date}, skipping.`);
        continue;
      }

      const participantsSnap = await db.collection("participants").get();
      if (participantsSnap.empty) {
        logger.warn("No participants in Firestore yet — skipping send. Add docs to the 'participants' collection.");
        continue;
      }

      const html = buildEmailHtml(day, feed.trip_title, feed.site_url);
      const subject = `${feed.trip_title} — ${day.display_date} (${day.city_label})`;

      let sent = 0, failed = 0;
      for (const doc of participantsSnap.docs) {
        const { email } = doc.data();
        if (!email) continue;
        try {
          await sendEmail(RESEND_API_KEY.value(), email, subject, html);
          sent++;
        } catch (err) {
          failed++;
          logger.error(`Failed to email ${email}`, err);
        }
      }

      await sentLogRef.set({
        sentAt: admin.firestore.FieldValue.serverTimestamp(),
        sentCount: sent,
        failedCount: failed
      });
      logger.info(`Sent ${day.date} agenda to ${sent} participant(s), ${failed} failure(s).`);
    }
  }
);
